version: "3"
services:
  discord-bot:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: discord-bot
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    command: npm run dev